### PR TITLE
Initial

### PR DESCRIPTION
**Pull request by alexeymorozov**
See fontist/fontist#221, fontist/fontist#223

### CODE REVIEW

**Comment by ronaldtse** [comment]
@alexeymorozov mergeable soon?

**Comment by alexeymorozov** [comment]
@ronaldtse There is left to implement archive detection before it can be used in `fontist`. I think of doing it in pure Ruby.

The issue that I could find no cross-platform file detection solution. They either require the `file` utility or the `libmagic` library. Since we have only several types of archives, pure Ruby implementation shouldn't take long but it's time anyway.

**Comment by alexeymorozov** [comment]
As a result the API could be used as:

```ruby
Excavator::Archive.new(archive_path).files(recursive_packages: true) do |f|
  install_font_file(f) if font_file?(f)
end
```

Without any need for formula's `extract` attribute.

**Comment by ronaldtse** [comment]
@alexeymorozov sounds good, look forward to it!

**Review by ronaldtse — APPROVED** [review]

**Pull request merged**
